#! /bin/sh

sxhkd &
nitrogen --restore &
picom -f &
$HOME/.config/polybar/launch.sh
nvidia-settings --load-config-only
gwe &

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

bspc config border_width        3 
bspc config window_gap          16 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "##D23D3D"
bspc config focused_border_color "#041e7e"
bspc config presel_feedback_color "#FF9100"

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
